"""phase5_kassenabschluss

Revision ID: 2c7393097a67
Revises: 69b3ccccef42
Create Date: 2026-07-16 06:57:24.598827
"""
from alembic import op
import sqlalchemy as sa


revision = '2c7393097a67'
down_revision = '69b3ccccef42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kassenabschluss',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kassenprofil_id', sa.Integer(), nullable=False),
    sa.Column('nummer', sa.String(length=40), nullable=False),
    sa.Column('benutzer_id', sa.Integer(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('von_zeitpunkt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bis_zeitpunkt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anzahl_verkaeufe', sa.Integer(), nullable=False),
    sa.Column('waren_cent', sa.Integer(), nullable=False),
    sa.Column('pfand_cent', sa.Integer(), nullable=False),
    sa.Column('gesamt_cent', sa.Integer(), nullable=False),
    sa.Column('bar_cent', sa.Integer(), nullable=False),
    sa.Column('anfangsbestand_cent', sa.Integer(), nullable=False),
    sa.Column('erwartet_cent', sa.Integer(), nullable=False),
    sa.Column('gezaehlt_cent', sa.Integer(), nullable=True),
    sa.Column('differenz_cent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], ),
    sa.ForeignKeyConstraint(['kassenprofil_id'], ['kassenprofil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kassenabschluss_zahlart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('abschluss_id', sa.Integer(), nullable=False),
    sa.Column('zahlungsmethode_id', sa.Integer(), nullable=True),
    sa.Column('bezeichnung', sa.String(length=120), nullable=False),
    sa.Column('anzahl', sa.Integer(), nullable=False),
    sa.Column('betrag_cent', sa.Integer(), nullable=False),
    sa.Column('bar', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['abschluss_id'], ['kassenabschluss.id'], ),
    sa.ForeignKeyConstraint(['zahlungsmethode_id'], ['zahlungsmethode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verkauf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abschluss_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_verkauf_abschluss', 'kassenabschluss', ['abschluss_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verkauf', schema=None) as batch_op:
        batch_op.drop_constraint('fk_verkauf_abschluss', type_='foreignkey')
        batch_op.drop_column('abschluss_id')

    op.drop_table('kassenabschluss_zahlart')
    op.drop_table('kassenabschluss')
    # ### end Alembic commands ###
