"""phase1_phase2_initial

Revision ID: ad2e1fdd780d
Revises: 
Create Date: 2026-07-15 13:39:49.102884
"""
from alembic import op
import sqlalchemy as sa


revision = 'ad2e1fdd780d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('zeitpunkt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('benutzer', sa.String(length=120), nullable=False),
    sa.Column('aktion', sa.String(length=120), nullable=False),
    sa.Column('datensatz', sa.String(length=255), nullable=False),
    sa.Column('vorher', sa.Text(), nullable=False),
    sa.Column('nachher', sa.Text(), nullable=False),
    sa.Column('begruendung', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('druckauftrag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dokumenttyp', sa.String(length=60), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('drucker', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('versuche', sa.Integer(), nullable=False),
    sa.Column('letzte_fehlermeldung', sa.Text(), nullable=False),
    sa.Column('nachdruck', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geraet',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('seriennummer', sa.String(length=120), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rolle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('stufe', sa.Integer(), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('systemeinstellung',
    sa.Column('schluessel', sa.String(length=120), nullable=False),
    sa.Column('wert', sa.Text(), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('geaendert_am', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('schluessel')
    )
    op.create_table('verein',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('anschrift', sa.Text(), nullable=False),
    sa.Column('kontakt', sa.Text(), nullable=False),
    sa.Column('logo_pfad', sa.String(length=255), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benutzer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('rolle_id', sa.Integer(), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('fehlversuche', sa.Integer(), nullable=False),
    sa.Column('letzter_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rolle_id'], ['rolle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kassenprofil',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('verein_id', sa.Integer(), nullable=False),
    sa.Column('bonkopf', sa.Text(), nullable=False),
    sa.Column('bonfuss', sa.Text(), nullable=False),
    sa.Column('waehrung', sa.String(length=8), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verein_id'], ['verein.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kategorie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kassenprofil_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('farbe', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('sortierung', sa.Integer(), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['kassenprofil_id'], ['kassenprofil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pfandart',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kassenprofil_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kurzname', sa.String(length=60), nullable=False),
    sa.Column('betrag_cent', sa.Integer(), nullable=False),
    sa.Column('farbe', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('rueckgabe_erlaubt', sa.Boolean(), nullable=False),
    sa.Column('artikelticket_drucken', sa.Boolean(), nullable=False),
    sa.Column('steuersatz', sa.Integer(), nullable=False),
    sa.Column('sortierung', sa.Integer(), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('max_rueckgabe_menge', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kassenprofil_id'], ['kassenprofil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sitzung',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('benutzer_id', sa.Integer(), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.Column('letzte_aktivitaet', sa.DateTime(timezone=True), nullable=False),
    sa.Column('laeuft_ab_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('veranstaltung',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kassenprofil_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('beginn', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ende', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ort', sa.String(length=200), nullable=False),
    sa.Column('pfand_aktiv', sa.Boolean(), nullable=False),
    sa.Column('bonkopf', sa.Text(), nullable=False),
    sa.Column('logo_pfad', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kassenprofil_id'], ['kassenprofil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zahlungsmethode',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kassenprofil_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kurzname', sa.String(length=60), nullable=False),
    sa.Column('farbe', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('sortierung', sa.Integer(), nullable=False),
    sa.Column('schublade_oeffnen', sa.Boolean(), nullable=False),
    sa.Column('rueckgeld_berechnen', sa.Boolean(), nullable=False),
    sa.Column('negativ_erlaubt', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['kassenprofil_id'], ['kassenprofil.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artikel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kassenprofil_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kurzname', sa.String(length=80), nullable=False),
    sa.Column('preis_cent', sa.Integer(), nullable=False),
    sa.Column('kategorie_id', sa.Integer(), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('archiviert', sa.Boolean(), nullable=False),
    sa.Column('sortierung', sa.Integer(), nullable=False),
    sa.Column('artikelticket_modus', sa.String(length=20), nullable=False),
    sa.Column('steuersatz', sa.Integer(), nullable=False),
    sa.Column('artikelnummer', sa.String(length=60), nullable=False),
    sa.Column('barcode', sa.String(length=60), nullable=False),
    sa.Column('farbe', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('ausgabeort', sa.String(length=80), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kassenprofil_id'], ['kassenprofil.id'], ),
    sa.ForeignKeyConstraint(['kategorie_id'], ['kategorie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artikel_pfand_zuordnung',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artikel_id', sa.Integer(), nullable=False),
    sa.Column('pfandart_id', sa.Integer(), nullable=False),
    sa.Column('menge_pro_einheit', sa.Integer(), nullable=False),
    sa.Column('automatisch', sa.Boolean(), nullable=False),
    sa.Column('abweichender_betrag_cent', sa.Integer(), nullable=True),
    sa.Column('gueltig_ab', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gueltig_bis', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artikel_id'], ['artikel.id'], ),
    sa.ForeignKeyConstraint(['pfandart_id'], ['pfandart.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artikel_id', 'pfandart_id', name='uq_artikel_pfandart')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artikel_pfand_zuordnung')
    op.drop_table('artikel')
    op.drop_table('zahlungsmethode')
    op.drop_table('veranstaltung')
    op.drop_table('sitzung')
    op.drop_table('pfandart')
    op.drop_table('kategorie')
    op.drop_table('kassenprofil')
    op.drop_table('benutzer')
    op.drop_table('verein')
    op.drop_table('systemeinstellung')
    op.drop_table('rolle')
    op.drop_table('geraet')
    op.drop_table('druckauftrag')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
