"""phase3_verkauf

Revision ID: d721d2ce1511
Revises: ad2e1fdd780d
Create Date: 2026-07-15 20:07:25.661345
"""
from alembic import op
import sqlalchemy as sa


revision = 'd721d2ce1511'
down_revision = 'ad2e1fdd780d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('belegkreis',
    sa.Column('kassenprofil_id', sa.Integer(), nullable=False),
    sa.Column('letzte_nummer', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kassenprofil_id'], ['kassenprofil.id'], ),
    sa.PrimaryKeyConstraint('kassenprofil_id')
    )
    op.create_table('verkauf',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('belegnummer', sa.String(length=40), nullable=False),
    sa.Column('kassenprofil_id', sa.Integer(), nullable=False),
    sa.Column('veranstaltung_id', sa.Integer(), nullable=True),
    sa.Column('benutzer_id', sa.Integer(), nullable=False),
    sa.Column('zeitpunkt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('waren_cent', sa.Integer(), nullable=False),
    sa.Column('pfand_cent', sa.Integer(), nullable=False),
    sa.Column('gesamt_cent', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['benutzer_id'], ['benutzer.id'], ),
    sa.ForeignKeyConstraint(['kassenprofil_id'], ['kassenprofil.id'], ),
    sa.ForeignKeyConstraint(['veranstaltung_id'], ['veranstaltung.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kassenprofil_id', 'belegnummer', name='uq_verkauf_beleg')
    )
    op.create_table('verkaufsposition',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('verkauf_id', sa.Integer(), nullable=False),
    sa.Column('typ', sa.String(length=20), nullable=False),
    sa.Column('artikel_id', sa.Integer(), nullable=True),
    sa.Column('pfandart_id', sa.Integer(), nullable=True),
    sa.Column('bezeichnung', sa.String(length=200), nullable=False),
    sa.Column('einzelpreis_cent', sa.Integer(), nullable=False),
    sa.Column('menge', sa.Integer(), nullable=False),
    sa.Column('gesamt_cent', sa.Integer(), nullable=False),
    sa.Column('artikelticket_modus', sa.String(length=20), nullable=False),
    sa.Column('steuersatz', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artikel_id'], ['artikel.id'], ),
    sa.ForeignKeyConstraint(['pfandart_id'], ['pfandart.id'], ),
    sa.ForeignKeyConstraint(['verkauf_id'], ['verkauf.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zahlung',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('verkauf_id', sa.Integer(), nullable=False),
    sa.Column('zahlungsmethode_id', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.String(length=120), nullable=False),
    sa.Column('betrag_cent', sa.Integer(), nullable=False),
    sa.Column('gegeben_cent', sa.Integer(), nullable=False),
    sa.Column('rueckgeld_cent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['verkauf_id'], ['verkauf.id'], ),
    sa.ForeignKeyConstraint(['zahlungsmethode_id'], ['zahlungsmethode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zahlung')
    op.drop_table('verkaufsposition')
    op.drop_table('verkauf')
    op.drop_table('belegkreis')
    # ### end Alembic commands ###
