name: Minimal Debug Pipeline

on:
  push:
    branches: [ cicd-pipline ]

jobs:
  debug-job:
    runs-on: ubuntu-latest
    steps:
      - name: Test Runner
        run: echo "Wenn du das hier siehst, funktionieren die GitHub Server!"
